#!/usr/bin/env python3
"""Generate a stable Haskell facade over MAlonzo's numbered symbols."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SYMBOLS = {
    "type_fact_t": r"T_TypeFact_\d+",
    "type_fact_c": r"C_typeFact_\d+",
    "relation_fact_t": r"T_RelationFact_\d+",
    "relation_fact_c": r"C_relationFact_\d+",
    "subsort_rule_t": r"T_SubsortRule_\d+",
    "subsort_rule_c": r"C_subsortRule_\d+",
    "requirement_t": r"T_Requirement_\d+",
    "has_sort_c": r"C_hasSort_\d+",
    "all_of_c": r"C_allOf_\d+",
    "any_of_c": r"C_anyOf_\d+",
    "not_requirement_c": r"C_notRequirement_\d+",
    "predicate_fact_t": r"T_PredicateFact_\d+",
    "predicate_fact_c": r"C_predicateFact_\d+",
    "lexeme_fact_t": r"T_LexemeFact_\d+",
    "lexeme_fact_c": r"C_lexemeFact_\d+",
    "knowledge_base_t": r"T_KnowledgeBase_\d+",
    "knowledge_base_c": r"C_knowledgeBase_\d+",
    "edge_t": r"T_Edge_\d+",
    "edge_c": r"C_edge_\d+",
    "hole_t": r"T_Hole_\d+",
    "subject_hole_c": r"C_subjectHole_\d+",
    "object_hole_c": r"C_objectHole_\d+",
    "direction_t": r"T_Direction_\d+",
    "expand_c": r"C_expand_\d+",
    "contract_c": r"C_contract_\d+",
    "forget_context_t": r"T_ForgetContext_\d+",
    "forget_context_c": r"C_forgetContext_\d+",
    "certificate_t": r"T_RawCertificate_\d+",
    "certificate_c": r"C_rawCertificate_\d+",
    "runtime_clause_t": r"T_RuntimeClause_\d+",
    "runtime_clause_c": r"C_runtimeClause_\d+",
    "anchor_t": r"T_RawLexicalAnchor_\d+",
    "anchor_c": r"C_rawLexicalAnchor_\d+",
    "context_payload_t": r"T_RawContextPayload_\d+",
    "context_requires_c": r"C_rawRequires_\d+",
    "context_relation_c": r"C_rawRequiresRelation_\d+",
    "context_some_c": r"C_rawRequiresSome_\d+",
    "context_prefers_c": r"C_rawPrefers_\d+",
    "context_prefers_relation_c": r"C_rawPrefersRelation_\d+",
    "context_prefers_some_c": r"C_rawPrefersSome_\d+",
    "context_constraint_t": r"T_RawContextConstraint_\d+",
    "context_constraint_c": r"C_rawContextConstraint_\d+",
    "context_t": r"T_RawContext_\d+",
    "context_c": r"C_rawContext_\d+",
    "evidence_t": r"T_RawDiscourseEvidence_\d+",
    "evidence_c": r"C_targetSalient_\d+",
    "check": r"d_check_\d+",
    "runtime_check": r"d_runtimeCheck_\d+",
    "contextual_runtime_check": r"d_contextualRuntimeCheck_\d+",
    "context_layer_check": r"d_contextLayerCheck_\d+",
    "context_preference_check": r"d_contextPreferenceCheck_\d+",
    "preference_check": r"d_preferenceRuntimeCheck_\d+",
    "promotion_check": r"d_checkPromotion_\d+",
}


def resolve(source: str, label: str, pattern: str) -> str:
    matches = sorted(set(re.findall(rf"\b(?:{pattern})\b", source)))
    if len(matches) != 1:
        raise ValueError(
            f"expected exactly one generated symbol for {label}, found {matches}"
        )
    return matches[0]


def render(symbol: dict[str, str]) -> str:
    a = "Generated"
    return f"""-- Generated by scripts/generate_malonzo_api.py; do not edit.
module Metonymy.CheckerAPI
  ( TypeFact, typeFact
  , RelationFact, relationFact
  , SubsortRule, subsortRule
  , Requirement, hasSort, allOf, anyOf, notRequirement
  , PredicateFact, predicateFact
  , LexemeFact, lexemeFact
  , KnowledgeBase, knowledgeBase
  , Edge, edge
  , Hole, subjectHole, objectHole
  , Direction, expand, contract
  , ForgetContext, forgetContext
  , RawCertificate, rawCertificate
  , RuntimeClause, runtimeClause
  , RawLexicalAnchor, rawLexicalAnchor
  , RawContextPayload, rawRequires, rawRequiresRelation, rawRequiresSome
  , rawPrefers, rawPrefersRelation, rawPrefersSome
  , RawContextConstraint, rawContextConstraint
  , RawContext, rawContext
  , RawDiscourseEvidence, targetSalient
  , check, runtimeCheck, contextLayerCheck, contextPreferenceCheck
  , contextualRuntimeCheck, preferenceRuntimeCheck, checkPromotion
  ) where

import Data.Text (Text)
import qualified MAlonzo.Code.Metonymy.Checker as {a}

type TypeFact = {a}.{symbol["type_fact_t"]}
typeFact :: Text -> Text -> TypeFact
typeFact = {a}.{symbol["type_fact_c"]}

type RelationFact = {a}.{symbol["relation_fact_t"]}
relationFact :: Text -> Text -> Text -> RelationFact
relationFact = {a}.{symbol["relation_fact_c"]}

type SubsortRule = {a}.{symbol["subsort_rule_t"]}
subsortRule :: Text -> Text -> SubsortRule
subsortRule = {a}.{symbol["subsort_rule_c"]}

type Requirement = {a}.{symbol["requirement_t"]}
hasSort :: Text -> Requirement
hasSort = {a}.{symbol["has_sort_c"]}
allOf :: [Requirement] -> Requirement
allOf = {a}.{symbol["all_of_c"]}
anyOf :: [Requirement] -> Requirement
anyOf = {a}.{symbol["any_of_c"]}
notRequirement :: Requirement -> Requirement
notRequirement = {a}.{symbol["not_requirement_c"]}

type PredicateFact = {a}.{symbol["predicate_fact_t"]}
predicateFact :: Text -> Requirement -> Requirement -> Text -> Text -> PredicateFact
predicateFact = {a}.{symbol["predicate_fact_c"]}

type LexemeFact = {a}.{symbol["lexeme_fact_t"]}
lexemeFact :: Text -> Text -> LexemeFact
lexemeFact = {a}.{symbol["lexeme_fact_c"]}

type KnowledgeBase = {a}.{symbol["knowledge_base_t"]}
knowledgeBase ::
  [TypeFact] ->
  [RelationFact] ->
  [SubsortRule] ->
  [PredicateFact] ->
  [LexemeFact] ->
  KnowledgeBase
knowledgeBase = {a}.{symbol["knowledge_base_c"]}

type Edge = {a}.{symbol["edge_t"]}
edge :: Text -> Text -> Text -> Edge
edge = {a}.{symbol["edge_c"]}

type Hole = {a}.{symbol["hole_t"]}
subjectHole :: Hole
subjectHole = {a}.{symbol["subject_hole_c"]}
objectHole :: Hole
objectHole = {a}.{symbol["object_hole_c"]}

type Direction = {a}.{symbol["direction_t"]}
expand :: Direction
expand = {a}.{symbol["expand_c"]}
contract :: Direction
contract = {a}.{symbol["contract_c"]}

type ForgetContext = {a}.{symbol["forget_context_t"]}
forgetContext ::
  Bool -> Bool -> Bool -> Bool -> Bool -> Bool -> Bool -> ForgetContext
forgetContext = {a}.{symbol["forget_context_c"]}

type RawCertificate = {a}.{symbol["certificate_t"]}
rawCertificate ::
  Direction ->
  ForgetContext ->
  Text ->
  Hole ->
  Text ->
  Text ->
  Requirement ->
  Text ->
  Text ->
  [Edge] ->
  RawCertificate
rawCertificate = {a}.{symbol["certificate_c"]}

type RuntimeClause = {a}.{symbol["runtime_clause_t"]}
runtimeClause :: Text -> Text -> Text -> ForgetContext -> RuntimeClause
runtimeClause = {a}.{symbol["runtime_clause_c"]}

type RawLexicalAnchor = {a}.{symbol["anchor_t"]}
rawLexicalAnchor :: Text -> Text -> Text -> Integer -> Integer -> RawLexicalAnchor
rawLexicalAnchor = {a}.{symbol["anchor_c"]}

type RawContextPayload = {a}.{symbol["context_payload_t"]}
rawRequires :: Requirement -> RawContextPayload
rawRequires = {a}.{symbol["context_requires_c"]}
rawRequiresRelation :: Text -> Text -> RawContextPayload
rawRequiresRelation = {a}.{symbol["context_relation_c"]}
rawRequiresSome :: Text -> Requirement -> RawContextPayload
rawRequiresSome = {a}.{symbol["context_some_c"]}
rawPrefers :: Requirement -> RawContextPayload
rawPrefers = {a}.{symbol["context_prefers_c"]}
rawPrefersRelation :: Text -> Text -> RawContextPayload
rawPrefersRelation = {a}.{symbol["context_prefers_relation_c"]}
rawPrefersSome :: Text -> Requirement -> RawContextPayload
rawPrefersSome = {a}.{symbol["context_prefers_some_c"]}

type RawContextConstraint = {a}.{symbol["context_constraint_t"]}
rawContextConstraint :: RawLexicalAnchor -> RawContextPayload -> Text -> RawContextConstraint
rawContextConstraint = {a}.{symbol["context_constraint_c"]}

type RawContext = {a}.{symbol["context_t"]}
rawContext :: Text -> Text -> [RawContextConstraint] -> [Text] -> RawContext
rawContext = {a}.{symbol["context_c"]}

type RawDiscourseEvidence = {a}.{symbol["evidence_t"]}
targetSalient :: Text -> Text -> RawDiscourseEvidence
targetSalient = {a}.{symbol["evidence_c"]}

check :: KnowledgeBase -> RawCertificate -> Bool
check = {a}.{symbol["check"]}

runtimeCheck ::
  KnowledgeBase ->
  RuntimeClause ->
  RuntimeClause ->
  RawCertificate ->
  Bool
runtimeCheck = {a}.{symbol["runtime_check"]}

contextLayerCheck ::
  KnowledgeBase ->
  Text ->
  RawContext ->
  Text ->
  Bool
contextLayerCheck = {a}.{symbol["context_layer_check"]}

contextPreferenceCheck ::
  KnowledgeBase ->
  RawContextConstraint ->
  Text ->
  Bool
contextPreferenceCheck = {a}.{symbol["context_preference_check"]}

contextualRuntimeCheck ::
  KnowledgeBase ->
  RuntimeClause ->
  RuntimeClause ->
  RawCertificate ->
  Text ->
  RawContext ->
  Bool
contextualRuntimeCheck = {a}.{symbol["contextual_runtime_check"]}

preferenceRuntimeCheck ::
  KnowledgeBase ->
  RuntimeClause ->
  RuntimeClause ->
  RawCertificate ->
  Bool
preferenceRuntimeCheck = {a}.{symbol["preference_check"]}

checkPromotion ::
  RawCertificate ->
  Maybe RawDiscourseEvidence ->
  Bool
checkPromotion = {a}.{symbol["promotion_check"]}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    source = arguments.source.read_text(encoding="utf-8")
    resolved = {
        label: resolve(source, label, pattern)
        for label, pattern in SYMBOLS.items()
    }
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render(resolved), encoding="utf-8")


if __name__ == "__main__":
    main()
